### ISSUE TITLE
incremental ohlcv time bar generator

### ISSUE THREAD

**Issue by lrolsen** [nardew/talipp#73]
Hi,

Would it be possible to add an incremental ohlcv time bar generator that can be used a as input indicator?. That way you could just add price and quantity tuples to the bar generator and have it feed though to the downstream indicators.

**Comment by nardew** [comment]
Hi,
I am afraid I do not understand what you mean. Could you give an example?

**Comment by nardew** [comment]
No feedback for more than a month

**Comment by Morakhiyasaiyam** [comment]
What he wants is use main tuple object or dictionary for all high low open close time  value and update those value with time placed in that tuple to examine what new data are ready to adding and update only that tuple or dictionary and let all other indicator to acess value from it . I.e. for ema it can use close only from that tuple and for stochastic it can use all 3 values from that main dictionary!

Because now we have to add_value to all indicator! It's bit unusual !
